<?
$arBlockParams = array(
    "ACTIVE_DATE_FORMAT" => $arParams["LIST_ACTIVE_DATE_FORMAT"],
    "ADD_SECTIONS_CHAIN" => $arParams["LIST_ADD_SECTIONS_CHAIN"],
    "AJAX_MODE" => $arParams["AJAX_MODE"],
    "AJAX_OPTION_ADDITIONAL" => $arParams["AJAX_OPTION_ADDITIONAL"],
    "AJAX_OPTION_HISTORY" => $arParams["AJAX_OPTION_HISTORY"],
    "AJAX_OPTION_JUMP" => $arParams["AJAX_OPTION_JUMP"],
    "AJAX_OPTION_STYLE" => $arParams["AJAX_OPTION_STYLE"],
    "BXREADY_COLLECTION_DRAW" => "",
    "BXREADY_USER_TYPES" => $arParams["BXREADY_USER_TYPES_LISTPAGE"],
    "BXREADY_USER_TYPE_VARIANT" => $arParams["BXREADY_USER_TYPE_VARIANT_LISTPAGE"],
    "BXREADY_ELEMENT_DRAW" => ($arParams["BXREADY_USER_TYPES_LISTPAGE"] == "Y") ? $arParams["BXREADY_USER_TYPE_VARIANT_LISTPAGE"] : $arParams["BXREADY_ELEMENT_DRAW_LISTPAGE"],
    "BXREADY_LIST_BOOTSTRAP_GRID_STYLE" => $arParams["BXREADY_LIST_BOOTSTRAP_GRID_STYLE_LISTPAGE"],
    "BXREADY_LIST_XLG_CNT" => $arParams["BXREADY_LIST_XLG_CNT_LISTPAGE"],
    "BXREADY_LIST_LG_CNT" => $arParams["BXREADY_LIST_LG_CNT_LISTPAGE"],
    "BXREADY_LIST_MD_CNT" => $arParams["BXREADY_LIST_MD_CNT_LISTPAGE"],
    "BXREADY_LIST_SM_CNT" => $arParams["BXREADY_LIST_SM_CNT_LISTPAGE"],
    "BXREADY_LIST_XS_CNT" => $arParams["BXREADY_LIST_XS_CNT_LISTPAGE"],
    "BXREADY_LIST_TYPES" => 'elements',
    "BXREADY_SECTION_DRAW" => "",
    "CACHE_FILTER" => "Y",
    "CACHE_GROUPS" => $arParams['CACHE_GROUPS'],
    "CACHE_TIME" => $arParams['CACHE_TIME'],
    "CACHE_TYPE" => $arParams['CACHE_TYPE'],
    "CHECK_DATES" => $arParams['CHECK_DATES'],
    "DISPLAY_DATE" => "Y",
    "DETAIL_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["detail"],
    "DISPLAY_BOTTOM_PAGER" => $arParams["DISPLAY_BOTTOM_PAGER"],
    "DISPLAY_TOP_PAGER" => $arParams["DISPLAY_TOP_PAGER"],
    "FIELD_CODE" => $arParams["LIST_FIELD_CODE"],
    "FILTER_NAME" => "",
    "HIDE_LINK_WHEN_NO_DETAIL" => "N",
    "IBLOCK_ID" => $arParams["IBLOCK_ID"],
    "IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
    "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
    "INCLUDE_SUBSECTIONS" => $arParams["INCLUDE_SUBSECTIONS"],
    "NEWS_COUNT" => $arParams['LIST_MAX_NEWS_COUNT'],
    "PAGER_DESC_NUMBERING" => $arParams['PAGER_DESC_NUMBERING'],
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
    "PAGER_SHOW_ALL" => "N",
    "PAGER_SHOW_ALWAYS" => $arParams['PAGER_SHOW_ALWAYS'],
    "PAGER_TEMPLATE" => $arParams['PAGER_TEMPLATE'],
    "PAGER_TITLE" => $arParams['PAGER_TITLE'],
    "DETAIL_PAGE_URL_CAPTION" => $arParams["DETAIL_PAGE_URL_CAPTION"],
    "PARENT_SECTION" => $arCurSection["ID"],
    "PARENT_SECTION_CODE" => "",
    "PREVIEW_TRUNCATE_LEN" => "",
    "PROPERTY_CODE" => $arParams['LIST_PROPERTY_CODE'],
    "SET_BROWSER_TITLE" => "N",
    "SET_META_DESCRIPTION" => "N",
    "SET_META_KEYWORDS" => "N",
    "SET_TITLE" => "N",
    "MESSAGE_404" => $arParams["MESSAGE_404"],
    "SET_STATUS_404" => $arParams["SET_STATUS_404"],
    "SHOW_404" => $arParams["SHOW_404"],
    "FILE_404" => $arParams["FILE_404"],
    "SORT_BY1" => $arParams['LIST_SORT_BY1'],
    "SORT_BY2" => $arParams['LIST_SORT_BY2'],
    "SORT_ORDER1" => $arParams['LIST_SORT_ORDER1'],
    "SORT_ORDER2" => $arParams['LIST_SORT_ORDER2'],
    "BXREADY_ELEMENT_ADDCLASS" => $arParams["BXREADY_ELEMENT_ADDCLASS_LISTPAGE"],
    "BXREADY_USE_ELEMENTCLASS" => $arParams["BXREADY_USE_ELEMENTCLASS_LISTPAGE"],
    "BXREADY_ELEMENT_EXT_PARAMS" => $arParams["BXREADY_ELEMENT_EXT_PARAMS_LISTPAGE"],
    "BXREADY_VERTICAL_ALIGN" => $arParams["BXREADY_VERTICAL_ALIGN_LISTPAGE"],
	"BXR_LAZY_LOAD" => $arParams["BXR_LAZY_LOAD"],
);

foreach ($arParams as $cell=>$val){
    if (substr($cell, 0, 9) == 'BXR_PRST_'){
        $name = str_replace('_LISTPAGE', '', $cell);
        $arBlockParams[$name] = $val;
    }
}

$APPLICATION->IncludeComponent(
    "bxready.market2:block.list",
    ".default",
    $arBlockParams,
    false,
    array('HIDE_ICONS'=>'Y')
);
?>