<?php

IncludeTemplateLangFile($_SERVER['DOCUMENT_ROOT'] . '/bitrix/templates/' . SITE_TEMPLATE_ID . '/footer.php');

$number = 2;
$formParams = [];

$formParams['MOBILE_PHONE'] = array(
    "BUTTON_TEXT" => "",
    "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
    "BXR_FORM_SUBMIT_ICON" => "",
    "COMPONENT_TEMPLATE" => "built_in",
    "GROUPS" => array(
        0 => "2",
    ),
    "RESIZE_IMAGES" => "N",
    "SEND_EVENT" => "KZNC_NEW_FORM_RESULT_PHONE",
    "STATUS_NEW" => "N",
    "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
    "USE_CAPTCHA" => "N",
    "BXR_FORM_ID" => "bxr-mobile-phone",
    "FORM_TITLE" => GetMessage("RECALL_MESSAGE"),
    "IBLOCK_ID" => "9",
    "IBLOCK_TYPE" => "forms",
    "MAX_FILE_SIZE" => "0",
    "MODE" => "link",
    "NAME_FROM_PROPERTY" => "23",
    "POPUP_TITLE" => GetMessage("RECALL_MESSAGE"),
    "PROPERTY_CODES" => array(
        0 => "23",
        1 => "24",
        2 => "25",
        3 => "8572",
        //3 => "26",
    ),
    "IGNORE_GLOBAL_PARAMS" => "N",
    "PERSONAL_DATA" => "Y",
    "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
    "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
    "PERSONAL_DATA_URL" => "/processing-personal-data/",
    "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
    "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с", //GetMessage("PERSONAL_DATA_TEXT"),    
    "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
    "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
     "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['MOBILE_CONTACTS'] = array(
    "BUTTON_TEXT" => "",
    "REQUEST_LINK" => $_SERVER['HTTP_REFERER'],
    "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
    "BXR_FORM_SUBMIT_ICON" => "",
    "COMPONENT_TEMPLATE" => "built_in",
    "GROUPS" => array(
        0 => "2",
    ),
    "RESIZE_IMAGES" => "N",
    "SEND_EVENT" => "KZNC_NEW_FORM_RESULT_QUESTION",
    "STATUS_NEW" => "N",
    "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
    "USE_CAPTCHA" => "N",
    "BXR_FORM_ID" => "bxr-mobile-contacts",
    "FORM_TITLE" => GetMessage("QUESTION_MESSAGE"),
    "IBLOCK_ID" => "7",
    "IBLOCK_TYPE" => "forms",
    "MAX_FILE_SIZE" => "0",
    "MODE" => "link",
    "NAME_FROM_PROPERTY" => "10",
    "POPUP_TITLE" => GetMessage("QUESTION_MESSAGE"),
    "PROPERTY_CODES" => array(
        0 => "10",
        1 => "11",
        2 => "12",
        3 => "13",
        4 => "8570",
    ),
    "PERSONAL_DATA" => "Y",
    "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
    "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
    "PERSONAL_DATA_URL" => "/processing-personal-data/",
    "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
    "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с", //GetMessage("PERSONAL_DATA_TEXT"),    
    "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
    "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
    "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['PHONE_POPUP'] = array(
    "BUTTON_TEXT" => "",
    "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
    "BXR_FORM_SUBMIT_ICON" => "",
    "COMPONENT_TEMPLATE" => "popup",
    "EVENT_CLASS" => "open-answer-form",
    "GROUPS" => array(
        0 => "2",
    ),
    "RESIZE_IMAGES" => "N",
    "SEND_EVENT" => "KZNC_NEW_FORM_RESULT_PHONE",
    "STATUS_NEW" => "N",
    "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
    "USE_CAPTCHA" => "N",
    "BXR_FORM_ID" => "bxr-phone-popup",
    "FORM_TITLE" => GetMessage("RECALL_MESSAGE"),
    "IBLOCK_ID" => "9",
    "IBLOCK_TYPE" => "forms",
    "MAX_FILE_SIZE" => "0",
    "MODE" => "link",
    "NAME_FROM_PROPERTY" => "23",
    "POPUP_TITLE" => GetMessage("RECALL_MESSAGE"),
    "PROPERTY_CODES" => array(
        0 => "23",
        1 => "24",
        2 => "25",
        3 => "8572",
        //3 => "26",
    ),
    "IGNORE_GLOBAL_PARAMS" => "N",
    "PERSONAL_DATA" => "Y",
    "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
    "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
    "PERSONAL_DATA_URL" => "/processing-personal-data/",
    "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
    "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
    "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
    "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
    "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['CONSULT_POPUP'] = array(
    "BUTTON_TEXT" => "",
    "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
    "BXR_FORM_SUBMIT_ICON" => "",
    "COMPONENT_TEMPLATE" => "request_product",
    "EVENT_CLASS" => "open-answer-form",
    "GROUPS" => array(
        0 => "2",
    ),
    "RESIZE_IMAGES" => "N",
    "SEND_EVENT" => "KZNC_NEW_FORM_RESULT_PHONE",
    "STATUS_NEW" => "N",
    "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
    "USE_CAPTCHA" => "N",
    "BXR_FORM_ID" => "bxr-prodconsult-popup",
    "FORM_TITLE" => 'Нужна помощь с выбором товара? <br>Подберем подходящий вариант и проконсультируем по наличию.',
    "IBLOCK_ID" => "9",
    "IBLOCK_TYPE" => "forms",
    "MAX_FILE_SIZE" => "0",
    "MODE" => "link",
    "NAME_FROM_PROPERTY" => "23",
    "POPUP_TITLE" => 'Нужна помощь с выбором товара?',
    "PROPERTY_CODES" => array(
        0 => "23",
        1 => "24",
        2 => "25",
        3 => "8572",
        //3 => "26",
    ),
    "IGNORE_GLOBAL_PARAMS" => "N",
    "PERSONAL_DATA" => "Y",
    "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
    "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
    "PERSONAL_DATA_URL" => "/processing-personal-data/",
    "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
    "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
    "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
    "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
    "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['FEEDBACK_POPUP'] = array(
  "BUTTON_TEXT" => "",
  "REQUEST_LINK" => $_SERVER['HTTP_REFERER'],
  "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
  "BXR_FORM_SUBMIT_ICON" => "",
  "COMPONENT_TEMPLATE" => "popup",
  "EVENT_CLASS" => "open-project-form",
  "GROUPS" => array(
    0 => "2",
  ),
  "RESIZE_IMAGES" => "N",
  "SEND_EVENT" => "KZNC_NEW_FORM_RESULT_QUESTION",
  "STATUS_NEW" => "N",
  "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
  "USE_CAPTCHA" => "N",
  "BXR_FORM_ID" => "bxr-feedback-popup",
  "FORM_TITLE" => GetMessage("QUESTION_MESSAGE"),
  "IBLOCK_ID" => "7",
  "IBLOCK_TYPE" => "forms",
  "MAX_FILE_SIZE" => "0",
  "MODE" => "link",
  "NAME_FROM_PROPERTY" => "10",
  "POPUP_TITLE" => GetMessage("QUESTION_MESSAGE"),
  "PROPERTY_CODES" => array(
    0 => "10",
    1 => "11",
    2 => "12",
    3 => "13",
    4 => "8570",
  ),
  "PERSONAL_DATA" => "Y",
  "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
  "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA_URL" => "/processing-personal-data/",
  "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
  "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
  "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
  "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['PROJECT_POPUP'] = array(
  "BUTTON_TEXT" => "",
  "REQUEST_LINK" => $_SERVER['HTTP_REFERER'],
  "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
  "BXR_FORM_SUBMIT_ICON" => "",
  "COMPONENT_TEMPLATE" => "popup",
  "EVENT_CLASS" => "open-answer-form",
  "GROUPS" => array(
    0 => "2",
  ),
  "RESIZE_IMAGES" => "N",
  "SEND_EVENT" => "KZNC_NEW_FORM_RESULT_QUESTION",
  "STATUS_NEW" => "N",
  "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
  "USE_CAPTCHA" => "N",
  "BXR_FORM_ID" => "bxr-project-popup",
  "FORM_TITLE" => 'Заказать проект',
  "IBLOCK_ID" => "57",
  "IBLOCK_TYPE" => "forms",
  "MAX_FILE_SIZE" => "0",
  "MODE" => "link",
  "NAME_FROM_PROPERTY" => "2195",
  "POPUP_TITLE" => GetMessage("QUESTION_MESSAGE"),
  "PROPERTY_CODES" => array(
    0 => "2195",
    1 => "2196",
    2 => "2197",
    3 => "2198",
    4 => "8573",
  ),
  "PERSONAL_DATA" => "Y",
  "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
  "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA_URL" => "/processing-personal-data/",
  "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
  "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
  "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
  "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['1CLICK_POPUP'] = array(
  "BUTTON_TEXT" => "",
  "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
  "BXR_FORM_SUBMIT_ICON" => "",
  "COMPONENT_TEMPLATE" => "request_product",
  "EVENT_CLASS" => "bxr-one-click-buy",
  "GROUPS" => array(
    0 => "2",
  ),
  "RESIZE_IMAGES" => "N",
  "SEND_EVENT" => "KZNC_NEW_FORM_ONE_CLICK",
  "STATUS_NEW" => "N",
  "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"), //Ваша заявка принята, в ближайшее время мы свяжемся с вами!
  "USE_CAPTCHA" => "N",
  "BXR_FORM_ID" => "bxr-one-click-buy-popup",
  "FORM_TITLE" => GetMessage("BXR_ONE_CLICK_BUY_TITLE"),
  "IBLOCK_ID" => "8",
  "IBLOCK_TYPE" => "forms",
  "MAX_FILE_SIZE" => "0",
  "MODE" => "link",
  "NAME_FROM_PROPERTY" => "19",
  "POPUP_TITLE" => GetMessage("BXR_ONE_CLICK_BUY_TITLE"),
  "PROPERTY_CODES" => array(
    0 => '14',
    1 => '15',
    2 => '16',
    3 => '17',
    4 => '18',
    5 => '19',
    6 => '20',
    7 => '21',
    8 => '22',
	9 => '8564',
  ),
  "PERSONAL_DATA" => "Y",
  "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
  "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA_URL" => "/processing-personal-data/",
  "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
  "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
  "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
  "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA2_URL" => "/privacy-policy/",
  "PROPERTY_CODES_REQUIRED" => array(
    0 => '20',
  ),
);

$formParams['REQUEST_PRODUCT'] = array(
  "BUTTON_TEXT" => "",
  "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
  "BXR_FORM_SUBMIT_ICON" => "",
  "COMPONENT_TEMPLATE" => "request_product",
  "EVENT_CLASS" => "bxr-trade-request",
  "GROUPS" => array(
    0 => "2",
  ),
  "RESIZE_IMAGES" => "N",
  "SEND_EVENT" => "KZNC_NEW_FORM_REQUEST",
  "STATUS_NEW" => "N",
  "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
  "USE_CAPTCHA" => "N",
  "BXR_FORM_ID" => "bxr-request-product-popup",
  "FORM_TITLE" => GetMessage("BXR_REQUEST_FORM_TITLE"),
  "IBLOCK_ID" => "10",
  "IBLOCK_TYPE" => "forms",
  "MAX_FILE_SIZE" => "0",
  "MODE" => "link",
  "NAME_FROM_PROPERTY" => "31",
  "POPUP_TITLE" => GetMessage("BXR_REQUEST_FORM_TITLE"),
  "PROPERTY_CODES" => array(
    0 => "27",
    1 => "28",
    2 => "29",
    3 => "30",
    4 => "31",
    5 => "32",
    6 => "33",
    7 => "34",
    8 => "8571",
  ),
  "PERSONAL_DATA" => "Y",
  "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
  "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA_URL" => "/processing-personal-data/",
  "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
  "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
  "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
  "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['CHECK_EXIST'] = array(
  "BUTTON_TEXT" => "",
  "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
  "BXR_FORM_SUBMIT_ICON" => "",
  "COMPONENT_TEMPLATE" => "request_product",
  "EVENT_CLASS" => "bxr-check-exist",
  "GROUPS" => array(
    0 => "2",
  ),
  "RESIZE_IMAGES" => "N",
  "SEND_EVENT" => "KZNC_NEW_FORM_CHECK_EXIST",
  "STATUS_NEW" => "N",
  "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
  "USE_CAPTCHA" => "N",
  "BXR_FORM_ID" => "bxr-check-exist-popup",
  "FORM_TITLE" => "Уточнить срок поставки",
  "IBLOCK_ID" => "34",
  "IBLOCK_TYPE" => "forms",
  "MAX_FILE_SIZE" => "0",
  "MODE" => "link",
  "NAME_FROM_PROPERTY" => "1991",
  "POPUP_TITLE" => "Уточнить срок поставки",
  "PROPERTY_CODES" => array(
    0 => '1986',
    1 => '1987',
    2 => '1988',
    3 => '1989',
    4 => '1990',
    5 => '1991',
    6 => '1992',
    7 => '1993',
	8 => '8563',
  ),
  "PERSONAL_DATA" => "Y",
  "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
  "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA_URL" => "/processing-personal-data/",
  "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
  "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
  "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
  "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['CHECK_PRICE'] = array(
  "BUTTON_TEXT" => "",
  "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
  "BXR_FORM_SUBMIT_ICON" => "",
  "COMPONENT_TEMPLATE" => "request_product",
  "EVENT_CLASS" => "bxr-check-price",
  "GROUPS" => array(
    0 => "2",
  ),
  "RESIZE_IMAGES" => "N",
  "SEND_EVENT" => "KZNC_NEW_FORM_CHECK_PRICE",
  "STATUS_NEW" => "N",
  "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
  "USE_CAPTCHA" => "N",
  "BXR_FORM_ID" => "bxr-check-price-popup",
  "FORM_TITLE" => "Уточнить цену",
  "IBLOCK_ID" => "58",
  "IBLOCK_TYPE" => "forms",
  "MAX_FILE_SIZE" => "0",
  "MODE" => "link",
  "NAME_FROM_PROPERTY" => "2301",
  "POPUP_TITLE" => "Уточнить цену",
  "PROPERTY_CODES" => array(
    0 => '2296',
    1 => '2297',
    2 => '2298',
    3 => '2299',
    4 => '2300',
    5 => '2301',
    6 => '2302',
    7 => '2303',
	8 => '8562',
  ),
  "PERSONAL_DATA" => "Y",
  "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
  "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA_URL" => "/processing-personal-data/",
  "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
  "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
  "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
  "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['TENDER_POPUP'] = array(
  "BUTTON_TEXT" => "",
  "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
  "BXR_FORM_SUBMIT_ICON" => "",
  "COMPONENT_TEMPLATE" => "popup",
  "EVENT_CLASS" => "open-answer-form",
  "GROUPS" => array(
    0 => "2",
  ),
  "RESIZE_IMAGES" => "N",
  "SEND_EVENT" => "KZNC_NEW_FORM_RESULT_TENDER",
  "STATUS_NEW" => "N",
  "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
  "USE_CAPTCHA" => "N",
  "BXR_FORM_ID" => "bxr-tender-popup",
  "FORM_TITLE" => 'Заявка на тендер или аукцион',
  "IBLOCK_ID" => "61",
  "IBLOCK_TYPE" => "forms",
  "MAX_FILE_SIZE" => "0",
  "MODE" => "link",
  "NAME_FROM_PROPERTY" => "8397",
  "POPUP_TITLE" => GetMessage("QUESTION_MESSAGE"),
  "PROPERTY_CODES" => array(
      0 => "8397",
      1 => "8398",
      2 => "8401",
      4 => "8399",
      5 => "8400",
      6 => "8402",
      7 => "8403",
      8 => "8404",
      9 => "8574",
  ),
  "IGNORE_GLOBAL_PARAMS" => "N",
  "PERSONAL_DATA" => "Y",
  "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
  "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA_URL" => "/processing-personal-data/",
  "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
  "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с", //GetMessage("PERSONAL_DATA_TEXT"),    
  "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
  "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['PARTNERSHIP_POPUP'] = array(
  "BUTTON_TEXT" => "",
  "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
  "BXR_FORM_SUBMIT_ICON" => "",
  "COMPONENT_TEMPLATE" => "popup",
  "EVENT_CLASS" => "open-answer-form",
  "GROUPS" => array(
    0 => "2",
  ),
  "RESIZE_IMAGES" => "N",
  "SEND_EVENT" => "KZNC_NEW_FORM_RESULT_PARTNERSHIP",
  "STATUS_NEW" => "N",
  "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
  "USE_CAPTCHA" => "N",
  "BXR_FORM_ID" => "bxr-partnership-popup",
  "FORM_TITLE" => 'Начать сотрудничество с выгодными условиями',
  "IBLOCK_ID" => "63",
  "IBLOCK_TYPE" => "forms",
  "MAX_FILE_SIZE" => "0",
  "MODE" => "link",
  "NAME_FROM_PROPERTY" => "8410",
  "POPUP_TITLE" => GetMessage("QUESTION_MESSAGE"),
  "PROPERTY_CODES" => array(
      0 => "8408",
      1 => "8409",
      2 => "8410",
      3 => "8411",
      4 => "8575",
  ),
  "IGNORE_GLOBAL_PARAMS" => "N",
  "PERSONAL_DATA" => "Y",
  "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
  "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA_URL" => "/processing-personal-data/",
  "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
  "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
  "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
  "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

$formParams['SERVICE_POPUP'] = array(
  "BUTTON_TEXT" => "",
  "BXR_FORM_SUBMIT_CAPTION" => GetMessage("BXR_FORM_SUBMIT_CAPTION_1"),
  "BXR_FORM_SUBMIT_ICON" => "",
  "COMPONENT_TEMPLATE" => "popup",
  "EVENT_CLASS" => "open-answer-form",
  "GROUPS" => array(
    0 => "2",
  ),
  "RESIZE_IMAGES" => "N",
  "SEND_EVENT" => "KZNC_NEW_FORM_RESULT_QUESTION",
  "STATUS_NEW" => "N",
  "USER_MESSAGE_ADD" => GetMessage("FORM_ANSWER_RESULT"),
  "USE_CAPTCHA" => "N",
  "BXR_FORM_ID" => "bxr-services-popup",
  "FORM_TITLE" => 'Обратная связь',
  "IBLOCK_ID" => "64",
  "IBLOCK_TYPE" => "forms",
  "MAX_FILE_SIZE" => "0",
  "MODE" => "link",
  "NAME_FROM_PROPERTY" => "8427",
  "POPUP_TITLE" => GetMessage("QUESTION_MESSAGE"),
  "PROPERTY_CODES" => array(
      0 => "8427",
      1 => "8428",
      2 => "8429",
      3 => "8430",
      4 => "8576",
  ),
  "IGNORE_GLOBAL_PARAMS" => "N",
  "PERSONAL_DATA" => "Y",
  "PERSONAL_DATA_TEXT" => "Нажимая на кнопку, я соглашаюсь на обработку персональных данных", //GetMessage("PERSONAL_DATA_TEXT"),
  "PERSONAL_DATA_CAPTION" => "Согласие на обработку персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA_URL" => "/processing-personal-data/",
  "PERSONAL_DATA_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.", //GetMessage("PERSONAL_DATA_ERROR")
  "PERSONAL_DATA2_TEXT" => "Нажимая на кнопку, я соглашаюсь с ", //GetMessage("PERSONAL_DATA_TEXT"),    
  "PERSONAL_DATA2_ERROR" => "Обработка вашей заявки без согласия на обработку персональных данных невозможна.",
  "PERSONAL_DATA2_CAPTION" => "политикой обработки персональных данных", //GetMessage("PERSONAL_DATA_CAPTION"),
  "PERSONAL_DATA2_URL" => "/privacy-policy/",
);

foreach ($formParams as $identity => $param) {
  $formParams[$identity]["IDENTITY"] = $identity;
  $formParams[$identity]["TARGET_URL"] = '/bitrix/components/bxready.market2/form.iblock/ajax/form.php';
  $formParams[$identity]["POST_FORM_URI"] = '/bitrix/components/bxready.market2/form.iblock/ajax/form.php';
  $formParams[$identity]["FORM_ID"] = $param['IBLOCK_ID'] . '_' . $identity;
}

return $formParams;
