<?global $APPLICATION;?>
<?if(!isset($BXRGeneral['SETTINGS']["main_page_slider_top_show"]) || $BXRGeneral['SETTINGS']["main_page_slider_top_show"]!="N"):?>
    <div class="bxr-b20 bxr-cloud-padding bxr-cloud-all">
        <?$APPLICATION->IncludeComponent(
	"bxready.market2:promo.controller", 
	".default", 
	array(
		"COMPONENT_TEMPLATE" => ".default",
		"BXR_PROMO_VARIANT" => "v2",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "3600000000",
		"BXR_PROMO_PREPARE_ID" => "slider",
		"IBLOCK_TYPE" => "content",
		"IBLOCK_ID" => "15",
		"PARENT_SECTION_CODE" => "main",
		"INCLUDE_SUBSECTIONS" => "Y",
		"NEWS_COUNT" => "10",
		"FIELD_CODE" => array(
			0 => "CODE",
			1 => "XML_ID",
			2 => "NAME",
			3 => "PREVIEW_PICTURE",
			4 => "DETAIL_TEXT",
			5 => "DETAIL_PICTURE",
			6 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "PROMO_HIDE_NAME",
			1 => "PROMO_LINK",
			2 => "",
		),
		"PROMO_CONTROLLER_TYPE" => "slider",
		"BXR_PROMO_IBLOCK_TYPE" => "content",
		"BXR_PROMO_IBLOCK_ID" => "12",
		"BXR_SLIDER_PARENT_SECTION_CODE" => "main",
		"BXR_PROMO_INCLUDE_SUBSECTIONS" => "Y",
		"BXR_PROMO_NEWS_COUNT" => "10",
		"BXR_PROMO_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_PICTURE",
			3 => "",
		),
		"BXR_PROMO_PROPERTY_CODE" => array(
			0 => "TEXT_COLOR",
			1 => "PROMO_HIDE_NAME",
			2 => "PROMO_LINK",
			3 => "PROMO_LINK_OPEN_NEW",
			4 => "LG_COL_COUNT",
			5 => "MD_COL_COUNT",
			6 => "SM_COL_COUNT",
			7 => "XS_COL_COUNT",
			8 => "NAME_COLOR",
			9 => "NAME_BACK_COLOR",
			10 => "TEXT_BACK_COLOR",
			11 => "PROMO_NO_EFFECT",
			12 => "EFFECT_ADD_COLOR",
			13 => "",
		),
		"BXR_SLIDER_IBLOCK_TYPE" => "content",
		"BXR_SLIDER_IBLOCK_ID" => "15",
		"BXR_SLIDER_SLIDER_FULL_SCREEN" => "Y",
		"BXR_SLIDER_SLIDER_FADE" => "Y",
		"BXR_SLIDER_SLIDER_SPEED" => "1000",
		"BXR_SLIDER_SLIDER_AUTOPLAY" => "Y",
		"BXR_SLIDER_SLIDER_AUTOPLAY_SPEED" => "4000",
		"BXR_SLIDER_HIDE_SLIDER_ARROWS_LISTPAGE" => "Y",
		"BXR_SLIDER_HIDE_MOBILE_SLIDER_ARROWS_LISTPAGE" => "Y",
		"BXR_SLIDER_LIST_SLIDER_MARKERS_LISTPAGE" => "Y",
		"BXR_SLIDER_HEIGHT" => "20vw",
		"BXR_SLIDER_CUSTOM_BREAKPOINT" => "Y",
		"BXR_SLIDER_CUSTOM_BREAKPOINT_LG" => "1200",
		"BXR_SLIDER_CUSTOM_HEIGHT_LG" => "23vw",
		"BXR_SLIDER_CUSTOM_HIDDEN_LG" => "N",
		"BXR_SLIDER_CUSTOM_BREAKPOINT_MD" => "992",
		"BXR_SLIDER_CUSTOM_HEIGHT_MD" => "26vw",
		"BXR_SLIDER_CUSTOM_HIDDEN_MD" => "N",
		"BXR_SLIDER_CUSTOM_BREAKPOINT_SM" => "768",
		"BXR_SLIDER_CUSTOM_HEIGHT_SM" => "34vw",
		"BXR_SLIDER_CUSTOM_HIDDEN_SM" => "N",
		"BXR_SLIDER_CUSTOM_BREAKPOINT_XS" => "0",
		"BXR_SLIDER_CUSTOM_HEIGHT_XS" => "32vw",
		"BXR_SLIDER_CUSTOM_HIDDEN_XS" => "N",
		"BXR_SLIDER_ADAPTIVE_MODE" => "Y",
		"BXR_SLIDER_CUSTOM_BREAKPOINT_XL" => "1920",
		"BXR_SLIDER_CUSTOM_HEIGHT_XL" => "20vw",
		"BXR_SLIDER_CUSTOM_HIDDEN_XL" => "N",
		"BXR_PROMO_PARENT_SECTION" => "0",
		"BXR_PROMO_PARENT_SECTION_CODE" => "",
		"BXR_PROMO_DISPLAY_TYPE" => "block",
		"BXR_PROMO_HOVER_EFFECT" => "approx",
		"BXR_PROMO_BLOCK_HEIGHT" => "",
		"BXR_SLIDER_PARENT_SECTION" => "0",
		"BXR_SLIDER_SLIDER_INFINITE" => "Y"
	),
	false
);?>
    </div>
<?endif;?>
<?if(!isset($BXRGeneral['SETTINGS']["main_page_promo_top_show"]) || $BXRGeneral['SETTINGS']["main_page_promo_top_show"]!="N"):?>
    <div class="bxr-b20 bxr-cloud-padding bxr-cloud-all">
        <?$APPLICATION->IncludeComponent(
	"bxready.market2:promo.controller", 
	".default", 
	array(
		"COMPONENT_TEMPLATE" => ".default",
		"BXR_PROMO_VARIANT" => "v2",
		"BXR_PROMO_PREPARE_ID" => "promo_top",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"IBLOCK_TYPE" => "content",
		"IBLOCK_ID" => "12",
		"INCLUDE_SUBSECTIONS" => "Y",
		"NEWS_COUNT" => "10",
		"FIELD_CODE" => array(
			0 => "CODE",
			1 => "XML_ID",
			2 => "NAME",
			3 => "PREVIEW_PICTURE",
			4 => "DETAIL_TEXT",
			5 => "DETAIL_PICTURE",
			6 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "PROMO_HIDE_NAME",
			1 => "PROMO_LINK",
			2 => "",
		),
		"PROMO_CONTROLLER_TYPE" => "promo",
		"BXR_PROMO_IBLOCK_TYPE" => "content",
		"BXR_PROMO_IBLOCK_ID" => "12",
		"BXR_PROMO_PARENT_SECTION_CODE" => "main",
		"BXR_PROMO_INCLUDE_SUBSECTIONS" => "Y",
		"BXR_PROMO_NEWS_COUNT" => "10",
		"BXR_PROMO_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_PICTURE",
			3 => "",
		),
		"BXR_PROMO_PROPERTY_CODE" => array(
			0 => "PROMO_HIDE_NAME",
			1 => "PROMO_LINK",
			2 => "PROMO_LINK_OPEN_NEW",
			3 => "LG_COL_COUNT",
			4 => "MD_COL_COUNT",
			5 => "SM_COL_COUNT",
			6 => "XS_COL_COUNT",
			7 => "NAME_COLOR",
			8 => "TEXT_COLOR",
			9 => "NAME_BACK_COLOR",
			10 => "TEXT_BACK_COLOR",
			11 => "PROMO_NO_EFFECT",
			12 => "EFFECT_ADD_COLOR",
			13 => "",
		),
		"BXR_PROMO_DISPLAY_TYPE" => "block",
		"BXR_PROMO_HOVER_EFFECT" => "volbat",
		"BXR_SLIDER_IBLOCK_TYPE" => "content",
		"BXR_SLIDER_IBLOCK_ID" => "15",
		"BXR_SLIDER_SLIDER_FULL_SCREEN" => "Y",
		"BXR_SLIDER_SLIDER_FADE" => "N",
		"BXR_SLIDER_SLIDER_SPEED" => "1500",
		"BXR_SLIDER_SLIDER_AUTOPLAY" => "N",
		"BXR_SLIDER_SLIDER_AUTOPLAY_SPEED" => "3000",
		"BXR_PROMO_BLOCK_HEIGHT" => "200"
	),
	false
);?>
    </div>
<?endif;?>