<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();

if (!empty($PL_IDS)) { 
	
	global $plViewedFilter;
	$plViewedFilter = ['ID' => $PL_IDS];

	$arViewedParams = array(
		"COMPONENT_TEMPLATE" => "bxready",
		"IBLOCK_TYPE" => "catalog_new",
		"IBLOCK_ID" => $PL_IBLOCK,
		"FILTER_NAME" => "plViewedFilter",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"CUSTOM_FILTER" => "",
		"HIDE_NOT_AVAILABLE" => "Y",
		"HIDE_NOT_AVAILABLE_OFFERS" => "Y",
		"ELEMENT_SORT_FIELD" => "ID",
		"ELEMENT_SORT_ORDER" => $PL_IDS,
		"ELEMENT_SORT_FIELD2" => "SORT",
		"ELEMENT_SORT_ORDER2" => "ASC",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "shows",
		"OFFERS_SORT_ORDER2" => "asc",
		"PAGE_ELEMENT_COUNT" => "4",
		"LINE_ELEMENT_COUNT" => "4",
		"PROPERTY_CODE" => array("COLOR"),
		"PROPERTY_CODE_MOBILE" => array(),
		"OFFERS_FIELD_CODE" => array
		(
			0 => "CODE",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "DETAIL_PICTURE",
		),
		"OFFERS_PROPERTY_CODE" => array
		(
			0 => "CML2_ARTICLE",
			1 => "PICTURES_SKU",
			2 => "SIZE",
			3 => "COLOR",
		),
		"OFFERS_LIMIT" => "0",
		"PRODUCT_DISPLAY_MODE" => "Y",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"OFFER_ADD_PICT_PROP" => "PICTURES_SKU",
		"OFFER_TREE_PROPS" => array
		(
			0 => "COLOR",
			1 => "SIZE",
		),
		"PRODUCT_SUBSCRIPTION" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"BXR_SHOW_MAX_QUANTITY" => "A",
		"SHOW_CLOSE_POPUP" => "N",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_SUBSCRIBE" => "Уведомить о поступлении",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"SECTION_URL" => "/catalog/#SECTION_CODE#/",
		"DETAIL_URL" => "/product/#ELEMENT_CODE#/",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_TITLE" => "N",
		"BROWSER_TITLE" => "-",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"SET_LAST_MODIFIED" => "N",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRICE_CODE" => array("BASE"),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => "RUB",
		"BASKET_URL" => "/personal/basket.php",
		"USE_PRODUCT_QUANTITY" => "Y",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(),
		"OFFERS_CART_PROPERTIES" => array("SIZE","COLOR"),
		"ADD_TO_BASKET_ACTION" => "",
		"DISPLAY_COMPARE" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_BASE_LINK" => "",
		"PAGER_PARAMS_NAME" => "",
		"LAZY_LOAD" => "N",
		"MESS_BTN_LAZY_LOAD" => "Показать ещё",
		"LOAD_ON_SCROLL" => "N",
		"SET_STATUS_404" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SHOW_404" => "Y",
		"FILE_404" => "",
		"MESSAGE_404" => "",
		"COMPATIBLE_MODE" => "Y",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"ENLARGE_PROP" => "",
		"COMPARE_PATH" => "/catalog/compare.php?action=#ACTION_CODE#",
		"MESS_BTN_COMPARE" => "Сравнение",
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"MESS_SHOW_MAX_QUANTITY" => "Наличие",
		"RELATIVE_QUANTITY_FACTOR" => "5",
		"MESS_RELATIVE_QUANTITY_MANY" => "много",
		"MESS_RELATIVE_QUANTITY_FEW" => "мало",
		"QUANTITY_IN_STOCK" => "В наличии",
		"QUANTITY_OUT_STOCK" => "Под заказ",
		"PAGE_BLOCK_TITLE" => $PL_TITLE,
		"HIDE_SECTION_DESCRIPTION" => "Y",
		"THIS_UNIC_ID" => "viewed",
		"REGION" => "",
		"BXR_AJAX_REGION_INFO" => "",
		"BXREADY_LIST_XLG_CNT_LISTPAGE" => "3",
		"BXREADY_LIST_LG_CNT_LISTPAGE" => "3",
		"BXREADY_LIST_MD_CNT_LISTPAGE" => "6",
		"BXREADY_LIST_SM_CNT_LISTPAGE" => "6",
		"BXREADY_LIST_XS_CNT_LISTPAGE" => "12",
		"BXREADY_ELEMENT_ADDCLASS_LISTPAGE" => "",
		"BXREADY_USE_ELEMENTCLASS_LISTPAGE" => "Y",
		"BXREADY_VERTICAL_ALIGN_LISTPAGE" => "Y",
		"BXREADY_ELEMENT_EXT_PARAMS_LISTPAGE" => "arrExtParams",
		"BXREADY_USER_TYPES_LISTPAGE" => "N",
		"BXREADY_ELEMENT_DRAW_LISTPAGE" => "ecommerce.m2.v1",
		"BXR_SHOW_RATING_LISTPAGE" => "N",
		"BXR_SHOW_ACTION_TIMER_LISTPAGE" => "N",
		"BXR_TILE_SHOW_PROPERTIES_LISTPAGE" => "Y",
		"BXREADY_LIST_MARKER_TYPE_LISTPAGE" => "circle.horizontal",
		"BXREADY_LIST_OWN_MARKER_USE_LISTPAGE" => "N",
		"BXR_SHOW_ARTICLE_LISTPAGE" => "Y",
		"BXR_SHOW_SLIDER_LISTPAGE" => "Y",
		"BXR_SLIDER_INTERVAL_LISTPAGE" => "3000",
		"BXR_USE_FAST_VIEW_LISTPAGE" => "N",
		"MESS_BTN_FAST_VIEW_LISTPAGE" => "Быстрый просмотр",
		"BXR_PRODUCT_BLOCKS_ORDER_LISTPAGE" => "picture,name,rating,avail,article,price,buttons,action_timer,props",
		"BXR_IMG_MAX_WIDTH_LISTPAGE" => "180",
		"BXR_IMG_MAX_HEIGHT_LISTPAGE" => "180",
		"SHOW_MAX_QUANTITY_LISTPAGE" => "Y",
		"BXR_SKU_PROPS_SHOW_TYPE_LISTPAGE" => "square",
		"BXR_SALELEADER" => array
		(
			"BXREADY_ELEMENT_ADDCLASS" => "",
			"BXREADY_USE_ELEMENTCLASS" => "Y",
			"BXREADY_VERTICAL_ALIGN" => "Y",
			"BXREADY_ELEMENT_EXT_PARAMS" => "arrExtParams",
			"BXREADY_USER_TYPES" => "N",
			"BXREADY_ELEMENT_DRAW" => "ecommerce.m2.v1",
			"BXR_SHOW_RATING" => "N",
			"BXR_SHOW_ACTION_TIMER" => "N",
			"BXR_TILE_SHOW_PROPERTIES" => "Y",
			"BXREADY_LIST_MARKER_TYPE" => "circle.horizontal",
			"BXREADY_LIST_OWN_MARKER_USE" => "N",
			"BXR_SHOW_ARTICLE" => "Y",
			"BXR_SHOW_SLIDER" => "Y",
			"BXR_SLIDER_INTERVAL" => "3000",
			"BXR_USE_FAST_VIEW" => "N",
			"MESS_BTN_FAST_VIEW" => "Быстрый просмотр",
			"BXREADY_LIST_XLG_CNT" => "3",
			"BXREADY_LIST_LG_CNT" => "4",
			"BXREADY_LIST_MD_CNT" => "6",
			"BXREADY_LIST_SM_CNT" => "6",
			"BXREADY_LIST_XS_CNT" => "12",
			"BXR_PRODUCT_BLOCKS_ORDER" => "picture,name,rating,avail,article,price,buttons,action_timer,props",
			"BXR_IMG_MAX_WIDTH" => "180",
			"BXR_IMG_MAX_HEIGHT" => "180",
			"SHOW_MAX_QUANTITY" => "Y",
			"BXR_SKU_PROPS_SHOW_TYPE" => "square",
		),
	);
	$APPLICATION->IncludeComponent(
		"bxready.market2:catalog.section",
		"bxready",
		$arViewedParams,
		false,
		array("HIDE_ICONS" => "Y")
	);
	
}
