<?
$elementID = $APPLICATION->IncludeComponent(
    "bxready.market2:block.detail",
    "",
    Array(
        "DISPLAY_DATE" => $arParams["DISPLAY_DATE"],
        "DISPLAY_NAME" => $arParams["DISPLAY_NAME"],
        "DISPLAY_PICTURE" => $arParams["DISPLAY_PICTURE"],
        "DISPLAY_PREVIEW_TEXT" => $arParams["DISPLAY_PREVIEW_TEXT"],
        "IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
        "IBLOCK_ID" => $arParams["IBLOCK_ID"],
        "FIELD_CODE" => $arParams["DETAIL_FIELD_CODE"],
        "PROPERTY_CODE" => $arParams["DETAIL_PROPERTY_CODE"],
        "DETAIL_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["detail"],
        "SECTION_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["section"],
        "META_KEYWORDS" => $arParams["META_KEYWORDS"],
        "META_DESCRIPTION" => $arParams["META_DESCRIPTION"],
        "BROWSER_TITLE" => $arParams["BROWSER_TITLE"],
        "SET_CANONICAL_URL" => $arParams["DETAIL_SET_CANONICAL_URL"],
        "DISPLAY_PANEL" => $arParams["DISPLAY_PANEL"],
        "SET_LAST_MODIFIED" => $arParams["SET_LAST_MODIFIED"],
        "SET_TITLE" => $arParams["SET_TITLE"],
        "MESSAGE_404" => $arParams["MESSAGE_404"],
        "SET_STATUS_404" => $arParams["SET_STATUS_404"],
        "SHOW_404" => $arParams["SHOW_404"],
        "FILE_404" => $arParams["FILE_404"],
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "ADD_SECTIONS_CHAIN" => $arParams["DETAIL_ADD_SECTIONS_CHAIN"],
        "ACTIVE_DATE_FORMAT" => $arParams["DETAIL_ACTIVE_DATE_FORMAT"],
        "CACHE_TYPE" => $arParams["CACHE_TYPE"],
        "CACHE_TIME" => $arParams["CACHE_TIME"],
        "CACHE_GROUPS" => $arParams["CACHE_GROUPS"],
        "USE_PERMISSIONS" => $arParams["USE_PERMISSIONS"],
        "GROUP_PERMISSIONS" => $arParams["GROUP_PERMISSIONS"],
        "DISPLAY_TOP_PAGER" => $arParams["DETAIL_DISPLAY_TOP_PAGER"],
        "DISPLAY_BOTTOM_PAGER" => $arParams["DETAIL_DISPLAY_BOTTOM_PAGER"],
        "PAGER_TITLE" => $arParams["DETAIL_PAGER_TITLE"],
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => $arParams["DETAIL_PAGER_TEMPLATE"],
        "PAGER_SHOW_ALL" => $arParams["DETAIL_PAGER_SHOW_ALL"],
        "CHECK_DATES" => $arParams["CHECK_DATES"],
        "ELEMENT_ID" => $arResult["VARIABLES"]["ELEMENT_ID"],
        "ELEMENT_CODE" => $arResult["VARIABLES"]["ELEMENT_CODE"],
        "IBLOCK_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["news"],
        "USE_SHARE" => $arParams["BXR_BUSINESS_SHOW_SOCIAL_SHARE"],
        "SHARE_HIDE" => $arParams["BXR_SHARE_HIDE"],
        "SHARE_TEMPLATE" => $arParams["BXR_SHARE_TEMPLATE"],
        "SHARE_HANDLERS" => $arParams["BXR_SHARE_HANDLERS"],
        "SHARE_SHORTEN_URL_LOGIN" => $arParams["BXR_SHARE_SHORTEN_URL_LOGIN"],
        "SHARE_SHORTEN_URL_KEY" => $arParams["BXR_SHARE_SHORTEN_URL_KEY"],
        "BXR_SHARE_BLOCK_TEXT" => $arParams["BXR_SHARE_BLOCK_TEXT"],
        "ADD_ELEMENT_CHAIN" => (isset($arParams["ADD_ELEMENT_CHAIN"]) ? $arParams["ADD_ELEMENT_CHAIN"] : ''),
        "BXR_FORM_SIDEBAR" => (isset($arParams["BXR_FORM_SIDEBAR"]) ? $arParams["BXR_FORM_SIDEBAR"] : 'N'),
        "BXR_FORMS"=> $extractFormParams,
        "BXR_PICTURE"=> $extractPictureParams,
        'BXR_DETAIL_TABS' => $extractTabsParams,
        'BXR_OFFERS_BLOCK' => array(
            'BXR_SHOW_OFFERS'=>$arParams['BXR_SHOW_OFFERS'],
            'BXR_SHOW_OFFERS_TITLE'=>$arParams['BXR_SHOW_OFFERS_TITLE'],
            'BXR_DISCOUNT_SHOW_TYPE'=>$arParams['BXR_DISCOUNT_SHOW_TYPE']
        ),
        "BXR_SLIDER_HEIGHT" => $arParams["CBXR_PICTURE_BXR_SLIDER_HEIGHT"],
        "BXR_SHOW_IMG_IN_FORM" => $arParams["BXR_SHOW_IMG_IN_FORM"],
        "BXR_SHOW_NAME_IN_FORM" => $arParams["BXR_SHOW_NAME_IN_FORM"],
        "REGION" => (isset($arParams["REGION"]) && !empty($arParams["REGION"])) ? $arParams["REGION"] : "",
    ),
    $component
);
?>